default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Shoping_App_development

test:
  <<: *default
  database: Shoping_App_test

production:
  <<: *default
  database: Shoping_App_production
  username: Shoping_App
  password: <%= ENV['SHOPING_APP_DATABASE_PASSWORD'] %>
